### ISSUE TITLE
Not starting on Ubuntu 17.10 

### ISSUE THREAD

**Issue by matteotanca** [bilelmoussaoui/Authenticator#39]
**Reporter info**

 ```
 * Distribution -
 * Gtk+ 3.0 version -
 * Desktop environment -
 ```
Gnome Shell 3.26

**Authenticator version**

**Actual issue**

flatpak run com.github.bilelmoussaoui.Authenticator/x86_64/stable
[DEBUG] 2018-03-22 18:41:30 Adding Application Menu
[DEBUG] 2018-03-22 18:41:30 Loading CSS
[DEBUG] 2018-03-22 18:41:30 SQL: Table 'accounts' does not exists
[DEBUG] 2018-03-22 18:41:31 SQL: Table 'accounts' created successfully
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/Authenticator/application.py", line 108, in do_activate
    window = Window.get_default()
  File "/app/lib/python3.5/site-packages/Authenticator/widgets/window.py", line 55, in get_default
    Window.instance = Window()
  File "/app/lib/python3.5/site-packages/Authenticator/widgets/window.py", line 48, in __init__
    self._build_widgets()
  File "/app/lib/python3.5/site-packages/Authenticator/widgets/window.py", line 61, in _build_widgets
    headerbar = HeaderBar.get_default()
  File "/app/lib/python3.5/site-packages/Authenticator/widgets/headerbar.py", line 117, in get_default
    HeaderBar.instance = HeaderBar()
  File "/app/lib/python3.5/site-packages/Authenticator/widgets/headerbar.py", line 109, in __init__
    self._build_widgets()
  File "/app/lib/python3.5/site-packages/Authenticator/widgets/headerbar.py", line 143, in _build_widgets
    self.generate_popover(right_box)
  File "/app/lib/python3.5/site-packages/Authenticator/widgets/headerbar.py", line 151, in generate_popover
    self.app.menu)
AttributeError: 'HeaderBar' object has no attribute 'app'

**Steps to reproduce (if you knew)**
Install it on ubuntu 17.10

**Other Note (feature-request, question, etc...)**

**Comment by matteotanca** [comment]
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=authenticator com.github.bilelmoussaoui.Authenticator
[DEBUG] 2018-03-22 19:01:57 Adding Application Menu
[DEBUG] 2018-03-22 19:01:57 Loading CSS
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/Authenticator/application.py", line 108, in do_activate
    window = Window.get_default()
  File "/app/lib/python3.5/site-packages/Authenticator/widgets/window.py", line 55, in get_default
    Window.instance = Window()
  File "/app/lib/python3.5/site-packages/Authenticator/widgets/window.py", line 48, in __init__
    self._build_widgets()
  File "/app/lib/python3.5/site-packages/Authenticator/widgets/window.py", line 61, in _build_widgets
    headerbar = HeaderBar.get_default()
  File "/app/lib/python3.5/site-packages/Authenticator/widgets/headerbar.py", line 117, in get_default
    HeaderBar.instance = HeaderBar()
  File "/app/lib/python3.5/site-packages/Authenticator/widgets/headerbar.py", line 109, in __init__
    self._build_widgets()
  File "/app/lib/python3.5/site-packages/Authenticator/widgets/headerbar.py", line 143, in _build_widgets
    self.generate_popover(right_box)
  File "/app/lib/python3.5/site-packages/Authenticator/widgets/headerbar.py", line 151, in generate_popover
    self.app.menu)
AttributeError: 'HeaderBar' object has no attribute 'app'

**Comment by bilelmoussaoui** [comment]
Oh, I know what causes this issue. Going to fix it pretty soon!

**Comment by bilelmoussaoui** [comment]
Fixed that on master. Created a new HOTFIX release, testing the app right now on flathub. Should be available in 1/2 hours when you run `flatpak update`.
