### ISSUE TITLE
Fails to start without XDG_CURRENT_DESKTOP being set

### ISSUE THREAD

**Issue by dankasak** [bilelmoussaoui/Authenticator#57]
**Reporter info**

 ```
 * Distribution - Gentoo
 * Gtk+ 3.0 version - 3.22.26
 * Desktop environment - 0.22.99.23326
 ```

**Authenticator version** - 0.2, from flatpak

**Actual issue** - When I try to run authenticator, I get:

[DEBUG] 2018-04-03 09:34:15 Adding Application Menu
[DEBUG] 2018-04-03 09:34:15 Loading CSS
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/Authenticator/application.py", line 115, in do_activate
    window = Window.get_default()
  File "/app/lib/python3.5/site-packages/Authenticator/widgets/window.py", line 55, in get_default
    Window.instance = Window()
  File "/app/lib/python3.5/site-packages/Authenticator/widgets/window.py", line 48, in __init__
    self._build_widgets()
  File "/app/lib/python3.5/site-packages/Authenticator/widgets/window.py", line 61, in _build_widgets
    headerbar = HeaderBar.get_default()
  File "/app/lib/python3.5/site-packages/Authenticator/widgets/headerbar.py", line 117, in get_default
    HeaderBar.instance = HeaderBar()
  File "/app/lib/python3.5/site-packages/Authenticator/widgets/headerbar.py", line 109, in __init__
    self._build_widgets()
  File "/app/lib/python3.5/site-packages/Authenticator/widgets/headerbar.py", line 141, in _build_widgets
    if not is_gnome():
  File "/app/lib/python3.5/site-packages/Authenticator/utils.py", line 29, in is_gnome
    return environ.get("XDG_CURRENT_DESKTOP").lower() == "gnome"
AttributeError: 'NoneType' object has no attribute 'lower'

I have to start with:

export XDG_CURRENT_DESKTOP=enlightenment
flatpak run com.github.bilelmoussaoui.Authenticator

**Comment by bilelmoussaoui** [comment]
Already fixed here https://github.com/bilelmoussaoui/Authenticator/pull/56
