### ISSUE TITLE
[Flatpak] DBus Error on run

### ISSUE THREAD

**Issue by alex285** [bilelmoussaoui/Authenticator#75]
Shame on you! haha!
```
flatpak run com.github.bilelmoussaoui.Authenticator 

Traceback (most recent call last):
  File "/app/bin/authenticator", line 31, in <module>
    from Authenticator import Application
  File "/app/lib/python3.5/site-packages/Authenticator/__init__.py", line 19, in <module>
    from .application import Application
  File "/app/lib/python3.5/site-packages/Authenticator/application.py", line 24, in <module>
    from .widgets import Window, AboutDialog
  File "/app/lib/python3.5/site-packages/Authenticator/widgets/__init__.py", line 19, in <module>
    from .window import Window
  File "/app/lib/python3.5/site-packages/Authenticator/widgets/window.py", line 22, in <module>
    from ..models import Logger, Settings, Database
  File "/app/lib/python3.5/site-packages/Authenticator/models/__init__.py", line 27, in <module>
    from .screenshot import GNOMEScreenshot
  File "/app/lib/python3.5/site-packages/Authenticator/models/screenshot.py", line 1, in <module>
    import dbus
ImportError: No module named 'dbus'
```

![screenshot from 2018-09-02 23-06-52](https://user-images.githubusercontent.com/11244308/44960279-24afd300-af05-11e8-8cce-e06e3cbf4896.png)

**Comment by boris-ning-usds** [comment]
Running into same issue. I'm on Ubuntu 18.

**Comment by fartbagxp** [comment]
Running into same issue off of Ubuntu 18.

**Comment by dsanchezseco** [comment]
same! Ubuntu 18.04.1

**Comment by bilelmoussaoui** [comment]
Fixed that https://github.com/flathub/com.github.bilelmoussaoui.Authenticator/pull/5
Coming soon to Flathub.
